### ISSUE TITLE
Display Customers that haven't placed an Order

### ISSUE THREAD

**Issue by hannahhall** [TutshillTornados/bangazon#11]
By using the URL parameter `/customers/?active=false`, the JSON response should only contain customers that don't have any orders placed yet.

**Comment by Mminner4248** [comment]
Current Functionality: Using the URL parameter /customers/?active=false, the JSON response contains customers that don't have any orders placed yet.

Fun Fact: Movie trailers were originally shown after the movie, which is why they are called trailers.
