### ISSUE TITLE
Allow developers to access Product resource

### ISSUE THREAD

**Issue by hannahhall** [TutshillTornados/bangazon#2]
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list of products, and GET a single product.

**Comment by Mminner4248** [comment]
Current functionality: User can GET a list of products, and GET a single product by URL and Postman using parameters.

Fun Fact: A human will eat on average 70 assorted insects and 10 spiders while sleeping.
