### ISSUE TITLE
Allow developers to access the Training Program resource

### ISSUE THREAD

**Issue by hannahhall** [TutshillTornados/bangazon#9]
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE (but only if the start date is in the future)

User should be able to GET a list, and GET a single item.

**Comment by Mminner4248** [comment]
Current Functionality: User can GET a list, and GET a single item using URL or Postman parameters. The parameters are set to destroy if date is in the future. 

Fun Fact: Billy goats urinate on their own heads to smell more attractive to females.
